// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using practica_backen.Helper;

#nullable disable

namespace practica_backen.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("practica_backen.Models.GuestRegister", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Habitacion")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Ingreso")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Salida")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("Primary");

                    b.HasIndex("Id")
                        .HasDatabaseName("FK_IndexIdGuest");

                    b.ToTable("Guest", (string)null);
                });

            modelBuilder.Entity("practica_backen.Models.RegisterLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Habitacion")
                        .HasColumnType("int");

                    b.Property<string>("IdHuesped")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Ingreso")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("Salida")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("Primary");

                    b.HasIndex("Id")
                        .HasDatabaseName("FK_IndexIdLog");

                    b.ToTable("Log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
